version: '2'

services:
  rabbitmq:
    image: 'bitnami/rabbitmq:3.9'
    restart: always
    environment:
      - RABBITMQ_PASSWORD=admin
      - RABBITMQ_USERNAME=admin
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - 'rabbit_data:/bitnami'
volumes:
  rabbit_data:
    driver: local

